language: php

php:
  - 7.0

sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - docker exec php-cli /bin/bash
  - php -v
  - ./vendor/bin/phpunit
