language: php

php:
  - 7.0

sudo: false

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - phpenv --version
  - ./vendor/bin/phpunit
